name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "78fafb98f6f24e7b80febe18e016dc03", preview_id = "78fafb98f6f24e7b80febe18e016dc03" }
]
